# Generated by Django 4.1.6 on 2023-06-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=20)),
                ('telephone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_chassis', models.IntegerField()),
                ('marque', models.CharField(max_length=20)),
                ('modele', models.CharField(max_length=30)),
                ('annee_validation', models.DateField()),
                ('kilometrage', models.CharField(max_length=30)),
                ('puissance', models.CharField(max_length=30)),
                ('prix', models.IntegerField()),
                ('carburant', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('etat', models.IntegerField()),
                ('img1', models.ImageField(blank=True, upload_to='profile')),
                ('img2', models.ImageField(blank=True, upload_to='profile')),
                ('img3', models.ImageField(blank=True, upload_to='profile')),
                ('img4', models.ImageField(blank=True, upload_to='profile')),
                ('img5', models.ImageField(blank=True, upload_to='profile')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fournisseur')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField()),
                ('date_mise_a_jour', models.DateField()),
                ('description_annonce', models.CharField(max_length=400)),
                ('gamme', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='profile')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voiture')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
            },
        ),
    ]
