# Generated by Django 4.1.6 on 2023-06-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='date_mise_a_jour',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='gamme',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='photo',
        ),
    ]
